### ISSUE TITLE
dbus service thread count

### ISSUE THREAD

**Issue by laped83** [ccxtechnologies/adbus#68]
Hi again :)

I got a small question regarding the thread usage of a adbus dbus service. 

Start a service like the following. I will get a single process with one thread. 

```
$ ps -eLf | grep receiver
laa       112097   24113  112097  9    1 21:08 pts/1    00:00:00 python3 ./receiver.py
laa       112101   22712  112101  0    1 21:08 pts/0    00:00:00 grep --color=auto recei


```

If I call foo method with:

`busctl call sub.domain.tld /tld/domain/sub/Test tld.domain.sub.TestInterface Foo`

I'll get 

```
$ ps -eLf | grep receiver
laa       112097   24113  112097  0    2 21:08 pts/1    00:00:00 python3 ./receiver.py
laa       112097   24113  112160  0    2 21:08 pts/1    00:00:00 python3 ./receiver.py
laa       112174   22712  112174  0    1 21:08 pts/0    00:00:00 grep --color=auto recei

```
The last thread never disappears again. I thought that only only one thread (the main thread) was used for the asyncio event loop 
tasks?

Now if I  call the foo method in parallel I see that the thread count rises to 3 and none is never stopped.

```
$ ps -eLf | grep recei
laa       112097   24113  112097  0    3 21:08 pts/1    00:00:00 python3 ./receiver.py
laa       112097   24113  112160  0    3 21:08 pts/1    00:00:00 python3 ./receiver.py
laa       112097   24113  112682  0    3 21:18 pts/1    00:00:00 python3 ./receiver.py
laa       113025   22712  113025  0    1 21:19 pts/0    00:00:00 grep --color=auto recei
```

This worries me a little so can you tell me if this is normal behaviour and where this happens in the code? :)

Regards
Lars Pedersen

**receiver.py service example**
```
#!/usr/bin/env python3
import adbus
import asyncio
import time
import logging

service_name = 'sub.domain.tld'
object_path = '/tld/domain/sub/Test'
object_interface = 'tld.domain.sub.TestInterface'

class FooService(adbus.server.Object):
    def __init__(self, service):
        super().__init__(service, object_path, object_interface)

    @adbus.server.method()
    def foo(self) -> str:
        time.sleep(10)
        return 'Foo'

loop = asyncio.get_event_loop()
service = adbus.Service(service_name, bus='system', replace_existing=True, allow_replacement=True)
obj = FooService(service)
loop.run_forever()
```

**Comment by charleseidsness** [comment]
Hi Lars,

That is sort of expected, but a little surprising. Method calls are run in an executor so that they don't block the mainloop when being processed. This is used to avoid possible deadlocks when method calls call methods on other applications which may call back to us, among other things.

If you don't set the executor (which you can do by passing an argument to the Method init method) it will use the default executor which is a thread-pool.

[Python run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor)

I would expect that once you hit the maximum threads in your default thread-pool it should start re-using them.

The surprising thing; to me at least, is that it doesn't reuse them as soon as they are available. I guess that's just how it works. We have a lot of test hours on this library and haven't seen massive amounts threads spawned on our systems so I think it's all working correctly, but I will start taking a closer look at it now on our running systems.

Thanks!
Charles

**Comment by laped83** [comment]
Okay thanks for the feedback. I can also see that you sometime ago has added the ability to use a different executor.

When will you tag a new release? I can also see that https://pypi.org/project/adbus/ is on a v1.0.1.

It will be so easier for me to use a released version when creating an upstreamed rule in the ptxdist(https://www.ptxdist.org/)

Again thanks for the great work!

Regards
Lars Pedersen..

**Comment by charleseidsness** [comment]
Sure, I just created a new release 1.1.2 and uploaded it to PyPi, or at least I think I did. I have to re-learn how to do it every-time.

**Comment by laped83** [comment]
Thanks. Looks like you have lost the LICENSE file in the src on pypi?

**Comment by charleseidsness** [comment]
Thanks! Just updated it with 1.1.3.
